name: bgen_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.11.0
  - r-ggplot2=3.4.0
  - r-base=4.1.3
  - pip:
    - dask==2023.10.0
    - ipython==8.16.1
    - matplotlib==3.8.0
    - numpy==1.26.1
    - pandas==2.1.1
    - seaborn==0.13.0

